version: '3'

services:
  nushell:
    image: ${DOCKER_REGISTRY}/nu:${DOCKER_TAG}
    build:
      context: ..
      dockerfile: docker/Package${PATCH}.Dockerfile
      args:
        base: ${BASE_IMAGE}
        artifact: ${NU_BINS}
